version: "3"

services:

  encoder:
    container_name: encoder
    build: .
    volumes:
        - .:/go/src
    environment:
      - "FAKEGCS=1"
    networks:
      - ms-encoder
    extra_hosts:
      - storage.gcs.io:172.17.0.1
  

  fakegcs:
    container_name: fakegcs
    image: fsouza/fake-gcs-server
    command: -public-host storage.gcs.io:4443
    ports:
      - "4443:4443"
    volumes:
      - ./storage/preload:/data
      - ./storage/uploads:/storage
    networks:
      - ms-encoder

  rabbit:
      image: "rabbitmq:3-management"
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
      ports:
        - "15672:15672"
        - "5672:5672"

networks:
  ms-encoder:
    driver: bridge
